# more colors here: https://superuser.com/a/1104214
set-window-option -g window-status-current-bg "colour43"

bind e setw synchronize-panes

# create new window with 4 panes, 2x2
bind m split-window -h \; split-window -v \; select-pane -L \; split-window -v \; select-pane -U
